swagger: '2.0'
info:
  version: '1.0'
  title: Argent Bank API documentation / Transactions API
  description: Seconde partie du projet Argent Bank
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /transactions:
    get:
      description: >-
        Visualiser toutes les transactions pour le mois en cours, groupées par
        compte
      security:
        - bearer: []
      responses:
        '200':
          description: Succès
          schema:
            type: array 
            items:
              $ref: '#/definitions/transaction'
        '401':
          description: Non autorisé. Identifiants incorrects
        '500':
          description: Erreur serveur
  
  /transactions/transactionId:
    get:
      description: Visualiser les détails d'une transaction
      security:
        - bearer: []
      parameters:
        - name: transactionId
          in: path
          description: ID de la transaction
          required: true
          type: string
      responses:
        '200':
          description: Succès. Renvoi les détails de la transaction
          schema:
            $ref: '#/definitions/transactionId'
        '401':
          description: Non autorisé. Identifiants incorrects
        '404':
          description: Transaction non trouvée.
        '500':
          description: Erreur serveur
  /transactions/transactionUpdate:
    put:
      description: Modifier la description ou le titre d'une transaction
      security:
        - bearer: []
      parameters:
        - in: path
          name: transactionUpdate
          description: ID de la transaction
          required: true
          type: string
        - in: body
          name: transaction
          description: Object représentant la nouvelle information
          required: true
          type: string
      responses:
        '200':
          description: Succès. La description ou le titre de la transaction a bien été modifié
          schema:
            type: array
            items:
              $ref:'#/definitions/transactionUpdate'
        '400':
          description: Echec. Vérifier les données
        '401':
          description: Non autorisé. Identifiants incorrects
        '404':
          description: Transaction non trouvée.
        '500':
          description: Erreur serveur

securityDefinitions:
  bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  transaction:
    type: object
    properties:
      montant: 
        type: number
      description:
        type: string
      titre: 
        type: string
        
  transactionId:
    type: object
    properties:
      id:
        type: string
      montant: 
        type: number
      description:
        type: string
      titre: 
        type: string
      date_transaction: 
        type: number

  transactionUpdate:
    type: object
    properties:
      description:
        type: string
      titre:
        type: string
